### ISSUE TITLE
Prettify the web player

### ISSUE THREAD

**Issue by kelimuttu** [kelimuttu/kartiniteknologi#29]
Right now it look a bit unproportional. Try to experiment with different player.

**Comment by shitiomatic** [comment]
https://simplecast.com/ maybe

**Comment by kelimuttu** [comment]
@shitiomatic thanks. We used [Buzzsprout](https://www.buzzsprout.com/) in the past, but couldn't maintain it since we're just bootstrapping. 

We're more looking for a web player for the website. So, things like 
- http://kolber.github.io/audiojs/
- https://github.com/greghub/green-audio-player
