### ISSUE TITLE
Add Github Actions

### ISSUE THREAD

**Issue by shitiomatic** [kelimuttu/kartiniteknologi#31]
Kalau boleh saya pengen nambahin Github Actions untuk auto publish ke branch gh-pages.

Supaca branch master di folder `docs` nya tidak perlu di commit setiap ada update baru.

**Comment by kelimuttu** [comment]
Halo @shitiomatic 

Terima kasih inisiatifnya. Boleh aja sih idenya. Saya juga sering lupa generate docs selama ini. Bisa lewat PR ngga ya? Belum  pernah setup Github Actions sebelumnya.

**Comment by shitiomatic** [comment]
Bisa kak, sipp

**Comment by kelimuttu** [comment]
Thanks!

**Comment by shitiomatic** [comment]
#33 done

**Comment by shitiomatic** [comment]
@kelimuttu c
